name: Cache Restore and Save Example

on: push

jobs:
  cache-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: dummy-dir
          key: dummy-key
          restore-keys: |
            restore-key-

      - name: Run dummy command
        id: run
        run: |
          mkdir -p dummy-dir
          date >> dummy-dir/file.txt
          echo "corpus_size=$(wc -l dummy-dir/file.txt)" >> $GITHUB_OUTPUT
          cat dummy-dir/file.txt >> $GITHUB_STEP_SUMMARY

      - name: Save cache
        uses: actions/cache/save@v3
        with:
          path: dummy-dir
          key: restore-key-${{ steps.run.outputs.corpus_size }}

  delete-cache:
    needs: cache-demo
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete cache with key "dummy-key"
        run: |
          curl -s -X DELETE \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/caches?key=dummy-key
