name: Cache Restore and Save Example

on: push

jobs:
  cache-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: dummy-dir
          key: dummy-key
          restore-keys: |
            restore-key-

      - name: Run dummy command
        run: mkdir -p dummy-dir && echo 123 > dummy-dir/file.txt

      - name: Generate timestamp
        id: timestamp
        run: echo "ts=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Save cache
        uses: actions/cache/save@v3
        with:
          path: dummy-dir
          key: restore-key-${{ steps.timestamp.outputs.ts }}
